### ISSUE TITLE
MAP support for HeaderToField

### ISSUE THREAD

**Issue by prestonmcgowan** [jcustenborder/kafka-connect-transform-common#71]
I am making use of the HeaderToField to attempt to filter messages from a message's header.
The message header I am making use of is added by replicator,  the provenance header for replicator (__replicator_id).

I attempted to add the HeaderToField transform, but the connect failed with the following error.
Configuration:
```
    "transforms" : "headerToField",
    "transforms.headerToField.type" : "com.github.jcustenborder.kafka.connect.transform.common.HeaderToField$Value",
    "transforms.headerToField.header.mappings" : "__replicator_id:MAP"
```

I had also tried STRING and BYTES, for grins, still complained about `MAP is not a supported type`.

Error:
```
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:196)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:122)
    at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:50)
    at org.apache.kafka.connect.runtime.WorkerSourceTask.sendRecords(WorkerSourceTask.java:339)
    at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:264)
    at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:185)
    at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:235)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
    used by: java.lang.UnsupportedOperationException: MAP is not a supported type.
    at com.github.jcustenborder.kafka.connect.utils.transformation.BaseKeyValueTransformation.processMap(BaseKeyValueTransformation.java:48)
    at com.github.jcustenborder.kafka.connect.utils.transformation.BaseKeyValueTransformation.process(BaseKeyValueTransformation.java:130)
    at com.github.jcustenborder.kafka.connect.utils.transformation.BaseKeyValueTransformation.apply(BaseKeyValueTransformation.java:192)
    at org.apache.kafka.connect.runtime.TransformationChain.lambda$apply$0(TransformationChain.java:50)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:146)
    at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:180)
    ... 11 more
```

**Comment by conradkleinespel** [comment]
@prestonmcgowan Did you find a solution?

**Comment by andriihrachov** [comment]
Same for me when using mongodb sink, but even without setting MAP

```
    transforms=headerToField
    transforms.headerToField.type=com.github.jcustenborder.kafka.connect.transform.common.HeaderToField$Value
    transforms.headerToField.header.mappings=x-event-type:BYTES:x_event_type
    ```

**Comment by shberlin** [comment]
Same for me. I assume, this happens when the Header is given as MAP instead of LIST. A proper MAP support would be awesome.

**Comment by rkudryashov** [comment]
I've got the same error while trying to extract a header of type String and make it a record's key:

```
    "transforms": "headerToField",
    "transforms.headerToField.type": "com.github.jcustenborder.kafka.connect.transform.common.HeaderToField$Key",
    "transforms.headerToField.header.mappings": "id:STRING",
```

```
sink-connector    | org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
sink-connector    |     at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:223)
sink-connector    |     at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:149)
sink-connector    |     at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:50)
sink-connector    |     at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:540)
sink-connector    |     at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:493)
sink-connector    |     at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:332)
sink-connector    |     at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:234)
sink-connector    |     at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:203)
sink-connector    |     at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
sink-connector    |     at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
sink-connector    |     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
sink-connector    |     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
sink-connector    |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
sink-connector    |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
sink-connector    |     at java.base/java.lang.Thread.run(Thread.java:829)
sink-connector    | Caused by: java.lang.UnsupportedOperationException: STRING is not a supported type.
sink-connector    |     at com.github.jcustenborder.kafka.connect.utils.transformation.BaseKeyValueTransformation.processString(BaseKeyValueTransformation.java:56)
sink-connector    |     at com.github.jcustenborder.kafka.connect.utils.transformation.BaseKeyValueTransformation.process(BaseKeyValueTransformation.java:152)
sink-connector    |     at com.github.jcustenborder.kafka.connect.utils.transformation.BaseKeyValueTransformation.apply(BaseKeyValueTransformation.java:192)
sink-connector    |     at org.apache.kafka.connect.runtime.TransformationChain.lambda$apply$0(TransformationChain.java:50)
sink-connector    |     at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:173)
sink-connector    |     at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:207)
kafka             | [2022-10-20 12:22:04,244] INFO [GroupCoordinator 1001]: Member[group.instance.id None, member.id connector-consumer-users-db-sink-connector3334331-0-80562dbf-ef0a-4d03-8ff7-c9b622d8e390] in group connect-users-db-sink-connector3334331 has left, removing it from the group (kafka.co
ordinator.group.GroupCoordinator)
```

So the error raises here: https://github.com/jcustenborder/connect-utils/blob/master/connect-utils/src/main/java/com/github/jcustenborder/kafka/connect/utils/transformation/BaseKeyValueTransformation.java#L56

@jcustenborder please tell us if it will be possible to use the header extraction feature in the future? If not, do you know of alternative approaches for this?

**Comment by rkudryashov** [comment]
I can't say if there was something wrong in the config above, but when I tried to extract a header to a record's value:

```
    "transforms.headerToField.type": "com.github.jcustenborder.kafka.connect.transform.common.HeaderToField$Value",
```

that worked without errors, so for me the issue is not a blocker

**Comment by jx2lee** [comment]
related PR opend (#99)

**Comment by setrawicana** [comment]
Bumping this up. Facing the same issue
